"""
asp generate — generate runtime adapter files for Claude Code, Gemini CLI, etc.

Translates installed ASP skills into native formats that Claude Code and
Gemini CLI understand: .claude/skills/*.md files and GEMINI.md blocks.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

from asp import __version__
from asp.core.manifest import load_manifest
from asp.core.registry import InstalledSkillsDB
from asp.errors import ASPError

console = Console()

_SUPPORTED_TARGETS = ["claude", "gemini", "mcp"]


def command(
    target: str = typer.Argument(
        ...,
        help="Target runtime adapter: 'claude', 'gemini', or 'mcp'.",
    ),
    skill_id: Optional[str] = typer.Option(
        None,
        "--skill",
        "-s",
        help="Generate adapter for a specific skill ID only. Defaults to all installed.",
    ),
    output_dir: Path = typer.Option(
        Path("."),
        "--output",
        "-o",
        help="Output directory. Defaults to current directory.",
    ),
) -> None:
    """
    Generate runtime adapter files for installed skills.

    Targets:
      claude  — Creates .claude/skills/{name}.md for Claude Code
      gemini  — Appends skill blocks to GEMINI.md for Gemini CLI
      mcp     — Shows the MCP server config JSON to add to your AI tool

    Examples:
      asp generate claude
      asp generate gemini
      asp generate mcp
    """
    if target not in _SUPPORTED_TARGETS:
        console.print(
            f"[red]✗ Unknown target '{target}'.[/red] "
            f"Supported: {', '.join(_SUPPORTED_TARGETS)}"
        )
        raise typer.Exit(1)

    db = InstalledSkillsDB()
    records = db.list_installed()

    if not records:
        console.print(
            "[yellow]⚠ No skills installed.[/yellow]\n"
            "  Install one first: [cyan]asp install github:owner/skill-repo[/cyan]"
        )
        raise typer.Exit(0)

    # Filter to specific skill if requested
    if skill_id:
        records = [r for r in records if r.get("id") == skill_id or r.get("name") == skill_id]
        if not records:
            console.print(f"[red]✗ Skill '{skill_id}' is not installed.[/red]")
            raise typer.Exit(1)

    if target == "claude":
        _generate_claude(records, db, output_dir)
    elif target == "gemini":
        _generate_gemini(records, db, output_dir)
    elif target == "mcp":
        _show_mcp_config()


# ---------------------------------------------------------------------------
# Claude Code adapter
# ---------------------------------------------------------------------------


def _generate_claude(records: list[dict], db: InstalledSkillsDB, output_dir: Path) -> None:
    """Generate .claude/skills/*.md adapter files for Claude Code."""
    claude_skills_dir = output_dir / ".claude" / "skills"
    claude_skills_dir.mkdir(parents=True, exist_ok=True)

    generated: list[str] = []

    for record in records:
        skill_id = record.get("id", "")
        manifest_path = db.get_installed_manifest_path(skill_id)

        if not manifest_path:
            console.print(f"  [yellow]⚠ Skipping '{record.get('name')}' — manifest not found[/yellow]")
            continue

        try:
            manifest = load_manifest(manifest_path)
        except ASPError as e:
            console.print(f"  [yellow]⚠ Skipping '{record.get('name')}': {e}[/yellow]")
            continue

        # Build adapter content
        lines = [
            f"<!-- AUTO-GENERATED by asp {__version__} — {manifest.id}@{manifest.version} -->",
            f"<!-- Do not edit manually. Run: asp generate claude -->",
            "",
            f"# Skill: {manifest.name} v{manifest.version}",
            "",
            f"> {manifest.description}",
            "",
            "## Instructions",
            "",
            manifest.instructions.strip(),
            "",
        ]

        if manifest.inputs:
            lines += ["## Input Parameters", ""]
            for inp in manifest.inputs:
                req = "required" if inp.required else f"optional, default: {inp.default}"
                lines.append(f"- **{inp.name}** (`{inp.type}`, {req}): {inp.description}")
            lines.append("")

        if manifest.outputs:
            lines += ["## Output", ""]
            for out in manifest.outputs:
                lines.append(f"- **{out.name}** (`{out.type}`): {out.description}")
            lines.append("")

        if manifest.examples:
            lines += ["## Example", ""]
            ex = manifest.examples[0]
            lines.append(f"*{ex.description}*")
            lines.append("")

        # Write file
        adapter_path = claude_skills_dir / f"{manifest.name}.md"
        adapter_path.write_text("\n".join(lines), encoding="utf-8")
        generated.append(adapter_path.name)
        console.print(f"  [green]✓[/green] Generated [cyan]{adapter_path}[/cyan]")

    if generated:
        console.print()
        console.print(Panel(
            Text.assemble(
                (f"Generated {len(generated)} skill adapter(s) for Claude Code\n\n", "green"),
                ("Location: ", "dim"), (str(claude_skills_dir), "cyan"), ("\n\n", ""),
                ("Claude Code reads .claude/skills/ automatically.\n", "white"),
                ("Open Claude Code in this directory to use these skills.\n", "dim"),
            ),
            title="[green]✓ Claude Code Adapters Ready[/green]",
            border_style="green",
        ))


# ---------------------------------------------------------------------------
# Gemini CLI adapter
# ---------------------------------------------------------------------------


def _generate_gemini(records: list[dict], db: InstalledSkillsDB, output_dir: Path) -> None:
    """Append skill blocks to GEMINI.md for Gemini CLI."""
    gemini_md = output_dir / "GEMINI.md"

    # Read existing content (to avoid duplicates)
    existing = gemini_md.read_text(encoding="utf-8") if gemini_md.exists() else ""
    asp_marker = "<!-- ASP MANAGED SKILLS START -->"
    asp_end_marker = "<!-- ASP MANAGED SKILLS END -->"

    # Strip existing ASP block if present
    if asp_marker in existing:
        before = existing[:existing.index(asp_marker)]
    else:
        before = existing

    blocks: list[str] = [
        "",
        asp_marker,
        "",
        "## Available Skills (managed by ASP)",
        "",
        f"*Auto-generated by asp {__version__}. Do not edit this section manually.*",
        "*Update with: `asp generate gemini`*",
        "",
    ]

    generated_count = 0
    for record in records:
        skill_id = record.get("id", "")
        manifest_path = db.get_installed_manifest_path(skill_id)

        if not manifest_path:
            continue

        try:
            manifest = load_manifest(manifest_path)
        except ASPError:
            continue

        blocks += [
            f"### {manifest.name} v{manifest.version}",
            "",
            f"{manifest.description}",
            "",
            "**Usage:** Ask Gemini to use this skill with natural language, e.g.:",
            f'*"Use the {manifest.name} skill to..."*',
            "",
        ]

        if manifest.inputs:
            blocks.append("**Inputs:**")
            for inp in manifest.inputs:
                req = "required" if inp.required else "optional"
                blocks.append(f"- `{inp.name}` ({req}): {inp.description}")
            blocks.append("")

        blocks += [
            "**Instructions:**",
            "",
            "```",
            manifest.instructions.strip(),
            "```",
            "",
            "---",
            "",
        ]
        generated_count += 1
        console.print(f"  [green]✓[/green] Added [cyan]{manifest.name}[/cyan] to GEMINI.md")

    blocks += [asp_end_marker, ""]

    # Write file
    new_content = before.rstrip() + "\n" + "\n".join(blocks)
    gemini_md.write_text(new_content, encoding="utf-8")

    console.print()
    console.print(Panel(
        Text.assemble(
            (f"Added {generated_count} skill(s) to GEMINI.md\n\n", "green"),
            ("Location: ", "dim"), (str(gemini_md), "cyan"), ("\n\n", ""),
            ("Open Gemini CLI in this directory to use these skills.\n", "white"),
            ("Gemini reads GEMINI.md as system context automatically.\n", "dim"),
        ),
        title="[green]✓ Gemini CLI Adapters Ready[/green]",
        border_style="green",
    ))


# ---------------------------------------------------------------------------
# MCP config display
# ---------------------------------------------------------------------------


def _show_mcp_config() -> None:
    """Display the MCP server configuration to add to Claude/Gemini."""
    import json

    mcp_config = {
        "mcpServers": {
            "asp": {
                "command": "asp",
                "args": ["mcp", "serve"],
                "description": "AI Skill Protocol — exposes installed skills as MCP prompts",
            }
        }
    }

    console.print(Panel(
        Text.assemble(
            ("Add this to your MCP client configuration:\n\n", "white"),
        ),
        title="[cyan]MCP Server Configuration[/cyan]",
        border_style="cyan",
    ))

    console.print("[bold]For Claude Code[/bold] — add to [cyan]~/.claude/claude_desktop_config.json[/cyan]:")
    console.print()
    console.print_json(json.dumps(mcp_config, indent=2))
    console.print()

    gemini_config = {
        "mcpServers": {
            "asp": {
                "command": "asp",
                "args": ["mcp", "serve"],
            }
        }
    }
    console.print("[bold]For Gemini CLI[/bold] — add to [cyan]~/.gemini/settings.json[/cyan]:")
    console.print()
    console.print_json(json.dumps(gemini_config, indent=2))
    console.print()
    console.print("[dim]After adding the config, restart your AI tool and run:[/dim]")
    console.print("[cyan]asp mcp serve[/cyan] [dim](this runs the MCP server)[/dim]")
